version: '3.8'

services:
  # Простой одиночный ARK сервер
  ark-server:
    image: drpsychick/arkserver:latest
    container_name: ark-${ARK_SERVER_MAP:-theisland}
    restart: unless-stopped
    
    ports:
      - "27015:27015"
      - "27015:27015/udp"
      - "7777:7777"
      - "7777:7777/udp"
      - "7778:7778"
      - "7778:7778/udp"
      - "32330:32330"
    
    volumes:
      - steam_data:/home/steam/.steam/steamapps
      - ark_server:/ark
      # Конфигурационные файлы
      - ./ark-config:/ark/config
      - ./ark-backups:/ark/backup
      - ./ark-logs:/ark/log
    
    environment:
      # Основные настройки сервера
      - am_ark_SessionName=${ARK_SESSION_NAME:-My ARK Server}
      - am_serverMap=${ARK_SERVER_MAP:-Fjordur}
      - am_ark_ServerAdminPassword=${ARK_ADMIN_PASSWORD:-k3yb04rdc4t}
      - am_ark_ServerPassword=${ARK_SERVER_PASSWORD:-}
      - am_ark_MaxPlayers=${ARK_MAX_PLAYERS:-20}
      
      # Порты
      - am_ark_QueryPort=${ARK_QUERY_PORT:-27015}
      - am_ark_Port=${ARK_GAME_PORT:-7778}
      - am_ark_RCONPort=${ARK_RCON_PORT:-32330}
      
      # Настройки обновлений и резервных копий
      - am_arkAutoUpdateOnStart=${ARK_AUTO_UPDATE_ON_START:-true}
      - am_arkwarnminutes=${ARK_WARN_MINUTES:-15}
      - BACKUP_ONSTART=${ARK_BACKUP_ON_START:-false}
      - VALIDATE_SAVE_EXISTS=${ARK_VALIDATE_SAVE_EXISTS:-false}
      
      # Моды
      - am_ark_GameModIds=${ARK_GAME_MOD_IDS:-}
      
      # Дополнительные настройки
      - am_ark_AltSaveDirectoryName=${ARK_ALT_SAVE_DIRECTORY_NAME:-SavedArks}
      - LOG_RCONCHAT=${ARK_LOG_RCON_CHAT:-0}
      - am_arkflag_crossplay=${ARK_FLAG_CROSSPLAY:-false}
      
      # Игровые множители (базовые, остальные в Game.ini)
      - am_ark_XPMultiplier=${ARK_XP_MULTIPLIER:-5.0}
      - am_ark_EnablePVEGamma=${ARK_ENABLE_PVE_GAMMA:-true}
      - am_ark_EnablePVPGamma=${ARK_ENABLE_PVP_GAMMA:-true}
      - am_ark_AllowCaveBuildingPvE=${ARK_ALLOW_CAVE_BUILDING_PVE:-true}
      - am_ark_DifficultyOffset=${ARK_DIFFICULTY_OFFSET:-1}
      - am_ark_NightTimeSpeedScale=${ARK_NIGHT_TIME_SPEED_SCALE:-2.0}
      - am_ark_DisableStructurePlacementCollision=${ARK_DISABLE_STRUCTURE_PLACEMENT_COLLISION:-true}
      - am_ark_AlwaysAllowStructurePickup=${ARK_ALWAYS_ALLOW_STRUCTURE_PICKUP:-true}
      - am_ark_ShowMapPlayerLocation=${ARK_SHOW_MAP_PLAYER_LOCATION:-true}
      - am_ark_ShowFloatingDamageText=${ARK_SHOW_FLOATING_DAMAGE_TEXT:-true}
      - am_ark_ServerCrosshair=${ARK_SERVER_CROSSHAIR:-true}
      
      # Кластер
      - ARKCLUSTER=${ARK_CLUSTER_ENABLED:-false}
      - am_arkopt_clusterid=${ARK_CLUSTER_ID:-}
    
    deploy:
      resources:
        limits:
          memory: ${DOCKER_MEMORY_LIMIT:-8g}
          cpus: '${DOCKER_CPU_LIMIT:-4}'
        reservations:
          memory: 4g
          cpus: '2'

volumes:
  steam_data:
    driver: local
    name: ark_steam_data
  
  ark_server:
    driver: local
    name: ark_server_data

networks:
  default:
    name: ark-network
    driver: bridge
